#!/usr/bin/env bash

set -euxo pipefail

# Prerequisites: 
# - jq
# - sed
# - skopeo
# installed in the image via Dockerfile(https://gitlab.cee.redhat.com/rhprod/rhprod-cli/-/raw/main/Dockerfile)

# Get the container image url and its tag.
ARGO_CD_IMAGE_URL='registry.redhat.io/openshift-gitops-1/argocd-rhel9@sha256:8b024159d03cf5da2e4beff0936dd36a3db1b168c29e4c64e9f162edb157ca63'
ARGO_CD_IMAGE_TAG='v1.19.0-8'

# Get the SHA id for the respective processor architectures.
ARGO_CD_IMAGE_SHA_X86='sha256:6fb646fbd35b779be50ceca8d12a8736ed43ebe4f40204ca28851db2e2cfdf20'
ARGO_CD_IMAGE_SHA_ARM='sha256:7ce92cc4c69bd9cd64e5dfedad15388be5d9404ac916731b86f5cf490993756b'

# Update the vars to be replaced in spec.in template file.
sed -i "s/REPLACE_ARGO_CD_CONTAINER_SHA_X86/${ARGO_CD_IMAGE_SHA_X86}/g" microshift-gitops.spec.in
sed -i "s/REPLACE_ARGO_CD_CONTAINER_SHA_ARM/${ARGO_CD_IMAGE_SHA_ARM}/g" microshift-gitops.spec.in
sed -i "s/REPLACE_ARGO_CD_VERSION/${ARGO_CD_IMAGE_TAG}/g" microshift-gitops.spec.in

# Update spec file too, as the file generation from the template spec.in file is run prior to the pre-build-script execution.
sed -i "s/REPLACE_ARGO_CD_CONTAINER_SHA_X86/${ARGO_CD_IMAGE_SHA_X86}/g" microshift-gitops.spec
sed -i "s/REPLACE_ARGO_CD_CONTAINER_SHA_ARM/${ARGO_CD_IMAGE_SHA_ARM}/g" microshift-gitops.spec
sed -i "s/REPLACE_ARGO_CD_VERSION/${ARGO_CD_IMAGE_TAG}/g" microshift-gitops.spec

# REDIS build steps

# Get the container image url.
REDIS_IMAGE_URL='registry.redhat.io/rhel9/redis-7@sha256:ac87259892180d63c99553c5f619bf5206ce47712a095aaaa63fabf7a9a3cfc1'
REDIS_IMAGE_TAG='9.7-1766414358'

# Get the SHA id for the respective processor architectures.
REDIS_IMAGE_SHA_X86='sha256:1be9e6e067a7595a5a51da709d262c1f4a5eca2fe2033450a9737a5354170c00'
REDIS_IMAGE_SHA_ARM='sha256:9a21acdd1cb1d3faf577c6d9d24045e5da86e2f6b1c1a4438dfcc80e21f112d6'

# Update the vars to be replaced in spec.in template file.
sed -i "s/REPLACE_REDIS_CONTAINER_SHA_X86/${REDIS_IMAGE_SHA_X86}/g" microshift-gitops.spec.in
sed -i "s/REPLACE_REDIS_CONTAINER_SHA_ARM/${REDIS_IMAGE_SHA_ARM}/g" microshift-gitops.spec.in

# Update spec file too, as the file generation from the template spec.in file is run prior to the pre-build-script execution.
sed -i "s/REPLACE_REDIS_CONTAINER_SHA_X86/${REDIS_IMAGE_SHA_X86}/g" microshift-gitops.spec
sed -i "s/REPLACE_REDIS_CONTAINER_SHA_ARM/${REDIS_IMAGE_SHA_ARM}/g" microshift-gitops.spec
